workflows:
  android-build:
    name: Android Build (Smart Assistant)
    environment:
      flutter: stable
      xcode: latest
      cocoapods: 1.16.2
      java: 17
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Set up Flutter and Android
        script: |
          flutter clean
          flutter pub get
          flutter doctor -v
          ./gradlew clean --no-daemon
      - name: Build Android
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - ibrahimalsattouf88@gmail.com
        notify:
          success: true
          failure: true

