workflows:
  android_release:
    name: Android Release
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        SUPABASE_URL: ${CM_SUPABASE_URL}
        SUPABASE_ANON_KEY: ${CM_SUPABASE_ANON_KEY}
        VA_BASE_URL: ${CM_VA_BASE_URL}
      groups:
        - mobile_env
    triggering:
      events:
        - api
      cancel_previous_builds: true
    scripts:
      - name: Flutter pub get
        script: flutter pub get
      - name: Android build (release)
        script: |
          export GRADLE_OPTS="-Xmx2048m -Dorg.gradle.daemon=false"
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - ${CM_NOTIFY_EMAIL:-}
        notify:
          success: true
          failure: true
