dependencies:
  flutter:
    sdk: flutter

  # الشبكة والبيئة
  http: ^1.2.2
  flutter_dotenv: ^5.1.0

  # الأذونات والمايك
  permission_handler: ^12.0.1
  # (لا تضف permission_handler_android يدويًا؛ يجي ترانزيتيف)

  # التعرف الصوتي
  speech_to_text: ^7.3.0

  # واجهة
  cupertino_icons: ^1.0.8
